# see available mappings on src/maqui_joy/xbox.py

# pause button
b_pause: 'START'

b_tablet_reset: 'X'

b_photo: 'Y'
b_life: 'A'
b_tablet_logo: 'B'

# increment buttons
b_increment: 'UP'
b_decrement: 'DOWN'

# say phrase button
b_phrase_1: 'LEFT'
b_phrase_2: 'RIGHT'


b_behavior: 'LB'
# text: array of strings
tts_phrases: [
    " Hola !",
    " Bienvenido al Festival de Ingenieria y Ciencias",
    " Soy Maqui, un robot Pepper",
    " Soy un robot de servicio, disegnado para acompagnar y ayudar a los humanos",
    " En estos momentos trabajo en el laboratorio de robotica, \\pau=500\\ con mi amigo Bender y mi equipo Uchile Jom Breiquers",
    " Con mi equipo participamos todos los agnos en la competencia robocup!  \\pau=500\\  Este agno logramos el tercer lugar!",
    " Me encanta el festival, hay muchos robots como yo!  \\pau=500\\  a mi lado, esta mi amigo Bender, un robot de servicio igual que yo \\pau=1000\\ Aqui al frente podemos ver a los pequegnos Naos jugando futbol \\pau=500\\ por ultimo no olviden visitar la pequegna ciudad  de patitos Duckietown",
    " Festival ",
    " Cual es el estilo de musica favorito de los robots? \\pau=2500\\ Heavy Metal ^start(animations/Stand/Emotions/Positive/Laugh_3) \\pau=1000\\ "]

b_animation: 'RB'

animations: [
    "Stand/Waiting/Robot_1",
    "Stand/Waiting/SpaceShuttle_1",
    "Stand/Waiting/Zombie_1",
    'dance_saxo/guitar'
    ]
