# see available mappings on src/maqui_joy/xbox.py

# pause button
b_pause: 'START'
b_start_head: 'A'
b_stop_head: 'B'
# increment buttons
b_increment: 'UP'
b_decrement: 'DOWN'

# say phrase button
b_phrase_1: 'LEFT'
b_phrase_2: 'RIGHT'

tts_phrases: [
    " Hola !",
    " Hola !",
    " Me llamo Maqui ",
    " Trabajo en el laboratorio de robótica de esta Facultad con mi amigo Bender y mi equipo Uchile Homebreakers",
    " Soy un robot de servicio, diseñado para acompañar y ayudar a los humanos"
    ]