# see available mappings on src/maqui_joy/xbox.py

# pause button
b_pause: 'START'

# movement axes
a_angular: 'RS_HORZ'
a_linear_x:  'LS_VERT'
a_linear_y:  'LS_HORZ'

# cmd velocities
max_linear_vel: 1.0   # caution: do not use values higher than 0.7 
max_angular_vel: 1.0  # caution: do not use values higher than 0.8
